version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
